In [2]:
import numpy as np

In [3]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a[0,2]=9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [5]:
array_a[0]=9

In [6]:
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [7]:
array_a[:,0]=9

In [8]:
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [9]:
list_a = [8,7,8]
array_a[0] = list_a

In [10]:
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [11]:
type(array_a)

numpy.ndarray

In [12]:
array_a[:] =5
array_a

array([[5, 5, 5],
       [5, 5, 5]])