# characteristics of numpy functions

## Broadcasting

In [1]:
import numpy as np 

In [2]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [3]:
array_b=np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [4]:
matrix_c=np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.add(array_a , matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [6]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

used when we want to conduct elementwise operations but we don't have the same shape , so we broadcast (stretch) one variable to the size of the other to produce an output with the same shape

broadcasting rules: 
1- the arrays have the same shape 
2- the arrays have the same number of dimensions, and the length of each dimension is either common or 1
3- the arrays that have too few dimensions can have their shapes altered with a dimension 1, to satisfy the second rule. 


## Type Casting 

taking every element out of an array and changing it to a specified datatype 

In [7]:
np.add(array_b,matrix_c, dtype=np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

## Running over an axis

1- numpy breaks down an NDarray into smaller arrays of N-1 many dimensions 
2- Applies the function to each one 
we can use this feature to run a function along each row or column. 

In [8]:
np.mean(matrix_c,axis=0)

array([2.5, 3.5, 4.5])

axis = 0: finding the mean for each column of the array

axis= 1: finding the mean for each row of the array