In [1]:
import numpy as np

In [2]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [3]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a+2

array([ 9, 10, 11])

In [5]:
array_b+2

array([[3, 4, 5],
       [6, 7, 8]])

In [7]:
array_c = array_a + array_b[0]

In [8]:
array_c

array([ 8, 10, 12])