In [ ]:
import numpy as np 

# indices

In [10]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array_a[1] #suparray

array([4, 5, 6])

In [7]:
array_a[0][1] #specific_index

2

In [8]:
array_a[1,0] #specificindex

4

In [9]:
array_a[:,0] #interval_index

array([1, 4])

# negative indices 

Traversing the array backwords

In [13]:
array_b = np.array([1,2,3])
array_b

array([1, 2, 3])

In [14]:
array_b[-1]

3

In [15]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
array_a[-1]

array([4, 5, 6])

In [17]:
array_a[:,-1]

array([3, 6])

In [22]:
array_a[-1,-2]

5