In [1]:
import numpy as np 

In [2]:
array_a=np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
print(array_a)

[1 2 3]


In [6]:
array_a.shape


(3,)

In [8]:
array_b = np.array([[7,8,9],[10,11,12]])

In [9]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
type(array_b)

numpy.ndarray

In [11]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [12]:
array_b.shape

(2, 3)

In [13]:
array_c = np.array(12)

In [15]:
type(array_c)

numpy.ndarray

In [16]:
print(array_c)

12


In [17]:
array_c.shape

()

In [18]:
array_d = np.array([15])

In [19]:
type(array_d)

numpy.ndarray

In [20]:
array_d.shape

(1,)

In [26]:
list_a = [[1,2,3],[4,5,6]]

In [27]:
len(list_a)

2

In [28]:
array_f=np.array(list_a)

In [29]:
type(list_a)

list

In [30]:
type(array_f)

numpy.ndarray

In [31]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [32]:
print(array_f)

[[1 2 3]
 [4 5 6]]


In [33]:
array_f.shape

(2, 3)

In [37]:
len(list_a[0])

3

In [38]:
list_b=list_a[0] + list_a[1]

In [39]:
list_b

[1, 2, 3, 4, 5, 6]

In [40]:
array_y=array_f[0] + array_f[0]

In [42]:
array_y

array([2, 4, 6])