# Numpy datatypes

In [1]:
import numpy as np 

In [2]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array_a=np.array([[1,2,3],[4,5,6]], dtype='float32')
array_a


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [4]:
array_b=np.array([[1,2,3],[4,5,6]], np.float64)
array_b


array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
array_c=np.array([[1,2,3],[4,5,6]], np.complex64)
array_c


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [8]:
array_d=np.array([[1,0,3],[0,5,6]], np.bool)
array_d


C:\Users\Shaima Hameed\AppData\Local\Temp\ipykernel_6068\2632640364.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_d=np.array([[1,0,3],[0,5,6]], np.bool)


array([[ True, False,  True],
       [False,  True,  True]])

In [9]:
array_e=np.array([[1,2,3],[4,5,6]], np.str)
array_e


C:\Users\Shaima Hameed\AppData\Local\Temp\ipykernel_6068\1379646522.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_e=np.array([[1,2,3],[4,5,6]], np.str)


array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')