# working with arrays(slicing and squeeze function)


In [2]:
import numpy as np

## Slicing 

In [3]:
matrix_a= np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing 


creating a new array by taking chunks of values out of an existing one

slice: it can contain entire rows and columns of the original array, or just parts of them 

In [4]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int32)

In [6]:
matrix_a[0:1]

array([[1, 2, 3]])

In [7]:
matrix_a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
matrix_a[:1]

array([[1, 2, 3]])

In [10]:
matrix_a[1:]

array([[4, 5, 6]])

In [11]:
matrix_a[:-1]

array([[1, 2, 3]])

In [12]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [13]:
matrix_a[1:,1:]

array([[5, 6]])

## stepwise slicing

slicing, where we don't take consecutive values but values which are distance apart

In [14]:
matrix_b = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [15]:
matrix_b[::2,::] #slicing every other row

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [16]:
matrix_b[::,::2] #slicing every other column 

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [17]:
matrix_b[::2,::2] #every other value of every other row, starting from the first

array([[1, 1, 0],
       [4, 3, 0]])

In [18]:
matrix_b[::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

In [19]:
# by default(for negative indices and steps), we're starting from the bottom and moving up 

## Conditional Slicing 

In [20]:
matrix_c = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [21]:
matrix_c[:,0]

array([1, 3, 4])

In [22]:
matrix_c[:,0]>2

array([False,  True,  True])

In [23]:
matrix_c[:,:] >2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [24]:
matrix_c[matrix_c[:,:] >2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [25]:
matrix_c[(matrix_c[:,:] >2) & matrix_c[:,:] <=4]

array([1, 1, 1, 2, 0, 3, 6, 6, 7, 4, 4, 5, 3, 8, 0])

## Dimensions and the squeeze function 

In [26]:
matrix_d = np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_d

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [27]:
type(matrix_d[0,0]) #scalar

numpy.int32

In [28]:
type(matrix_d[0,0:1])

numpy.ndarray

In [29]:
print(matrix_d[0,0:1])

[1]


In [30]:
type(matrix_d[0:1,0:1])

numpy.ndarray

In [31]:
print(matrix_d[0:1,0:1])

[[1]]


In [33]:
print(matrix_d[0,0].shape) #scalar
print(matrix_d[0,0:1].shape) #vector
print(matrix_d[0:1,0:1].shape) #matrix

()
(1,)
(1, 1)


In [34]:
matrix_d[0:1,0:1].squeeze()

array(1)

In [35]:
#removes all unnecessary dimensions of an array

In [36]:
np.squeeze(matrix_d[0:1,0:1])

array(1)

In [39]:
print(matrix_d[0,0].squeeze().shape) 
print(matrix_d[0,0:1].squeeze().shape) 
print(matrix_d[0:1,0:1].squeeze().shape) 

()
()
()
